'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.34209
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("54")>  _
        Public Property user_lat() As Double
            Get
                Return CType(Me("user_lat"),Double)
            End Get
            Set
                Me("user_lat") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-124")>  _
        Public Property user_lon() As Double
            Get
                Return CType(Me("user_lon"),Double)
            End Get
            Set
                Me("user_lon") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("640")>  _
        Public Property user_ht_in_meters() As Double
            Get
                Return CType(Me("user_ht_in_meters"),Double)
            End Get
            Set
                Me("user_ht_in_meters") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("04/14/2015 09:38:00")>  _
        Public Property user_rundate() As Date
            Get
                Return CType(Me("user_rundate"),Date)
            End Get
            Set
                Me("user_rundate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-7")>  _
        Public Property user_tz() As Double
            Get
                Return CType(Me("user_tz"),Double)
            End Get
            Set
                Me("user_tz") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\Source\Satellite\Data\stardata.csv")>  _
        Public Property user_star_path() As String
            Get
                Return CType(Me("user_star_path"),String)
            End Get
            Set
                Me("user_star_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\Source\Satellite\Data\mcnames.txt")>  _
        Public Property user_mcnames_path() As String
            Get
                Return CType(Me("user_mcnames_path"),String)
            End Get
            Set
                Me("user_mcnames_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\Source\Satellite\Data\qs.mag.txt")>  _
        Public Property user_qsat_path() As String
            Get
                Return CType(Me("user_qsat_path"),String)
            End Get
            Set
                Me("user_qsat_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("E:\Source\Satellite\Data\visual.txt")>  _
        Public Property user_tle_path() As String
            Get
                Return CType(Me("user_tle_path"),String)
            End Get
            Set
                Me("user_tle_path") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Vanderhoof BC Canada")>  _
        Public Property user_loc_name() As String
            Get
                Return CType(Me("user_loc_name"),String)
            End Get
            Set
                Me("user_loc_name") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10000")>  _
        Public Property user_star_int() As Integer
            Get
                Return CType(Me("user_star_int"),Integer)
            End Get
            Set
                Me("user_star_int") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("1000")>  _
        Public Property user_sat_int() As Integer
            Get
                Return CType(Me("user_sat_int"),Integer)
            End Get
            Set
                Me("user_sat_int") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("True")>  _
        Public Property user_view_stereo() As Boolean
            Get
                Return CType(Me("user_view_stereo"),Boolean)
            End Get
            Set
                Me("user_view_stereo") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property user_ntp_onstart() As Boolean
            Get
                Return CType(Me("user_ntp_onstart"),Boolean)
            End Get
            Set
                Me("user_ntp_onstart") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property user_center_onzoom() As Boolean
            Get
                Return CType(Me("user_center_onzoom"),Boolean)
            End Get
            Set
                Me("user_center_onzoom") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("8")>  _
        Public Property user_sat_mag() As Double
            Get
                Return CType(Me("user_sat_mag"),Double)
            End Get
            Set
                Me("user_sat_mag") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property user_sat_limit() As Boolean
            Get
                Return CType(Me("user_sat_limit"),Boolean)
            End Get
            Set
                Me("user_sat_limit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.9")>  _
        Public Property user_star_transp() As Single
            Get
                Return CType(Me("user_star_transp"),Single)
            End Get
            Set
                Me("user_star_transp") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0.9")>  _
        Public Property user_star_bright() As Single
            Get
                Return CType(Me("user_star_bright"),Single)
            End Get
            Set
                Me("user_star_bright") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property user_sat_scale() As Integer
            Get
                Return CType(Me("user_sat_scale"),Integer)
            End Get
            Set
                Me("user_sat_scale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property user_star_scale() As Integer
            Get
                Return CType(Me("user_star_scale"),Integer)
            End Get
            Set
                Me("user_star_scale") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("10")>  _
        Public Property user_sat_buffer() As Integer
            Get
                Return CType(Me("user_sat_buffer"),Integer)
            End Get
            Set
                Me("user_sat_buffer") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property user_fov_alt() As Double
            Get
                Return CType(Me("user_fov_alt"),Double)
            End Get
            Set
                Me("user_fov_alt") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("45")>  _
        Public Property user_fov_azm() As Double
            Get
                Return CType(Me("user_fov_azm"),Double)
            End Get
            Set
                Me("user_fov_azm") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property user_fov_rotate() As Boolean
            Get
                Return CType(Me("user_fov_rotate"),Boolean)
            End Get
            Set
                Me("user_fov_rotate") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("0")>  _
        Public Property user_fov_rotation() As Double
            Get
                Return CType(Me("user_fov_rotation"),Double)
            End Get
            Set
                Me("user_fov_rotation") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("78.634468")>  _
        Public Property user_fov_ra() As Double
            Get
                Return CType(Me("user_fov_ra"),Double)
            End Get
            Set
                Me("user_fov_ra") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("-8.201641")>  _
        Public Property user_fov_dec() As Double
            Get
                Return CType(Me("user_fov_dec"),Double)
            End Get
            Set
                Me("user_fov_dec") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("25")>  _
        Public Property user_fov_width() As Double
            Get
                Return CType(Me("user_fov_width"),Double)
            End Get
            Set
                Me("user_fov_width") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("15")>  _
        Public Property user_fov_height() As Double
            Get
                Return CType(Me("user_fov_height"),Double)
            End Get
            Set
                Me("user_fov_height") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property user_fov_track() As Boolean
            Get
                Return CType(Me("user_fov_track"),Boolean)
            End Get
            Set
                Me("user_fov_track") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property user_fov_iscircle() As Boolean
            Get
                Return CType(Me("user_fov_iscircle"),Boolean)
            End Get
            Set
                Me("user_fov_iscircle") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property user_fov_useRA() As Boolean
            Get
                Return CType(Me("user_fov_useRA"),Boolean)
            End Get
            Set
                Me("user_fov_useRA") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("False")>  _
        Public Property user_fov_show() As Boolean
            Get
                Return CType(Me("user_fov_show"),Boolean)
            End Get
            Set
                Me("user_fov_show") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.SeeSatVB.My.MySettings
            Get
                Return Global.SeeSatVB.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
